# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c34ea24ed72be4836118bd790919e33975c2085e0682a0ec8a08814b9149d448235d4f7f08cafc468fbea22ad92fbb9068f07b0f35e5f96f7d3296178d751c

test:
  secret_key_base: ccbdcffd9d3de7c9bdb26ba0c84dd9177bc162c6af33d9f4c5018e376854aa35ec0fb2d91f42fdd8ed1844d6d5c9b22ef0bf89488622e67f606a3f472844c7c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
